### ISSUE TITLE
Solution architecture for the whole application

### ISSUE THREAD

**Issue by plumsirawit** [plumsirawit/task-pdf-writer#13]
- [x] Design the UX flow for user
- [x] Design the database
- [x] Design pages and their respective logic
- [x] Choose frameworks/tools to use (i.e. database, authentication, state management, styling)

Idea: decoupled but centralized (try to make it as easiest as possible to install/reuse)

Also, look forward to maintainability and stability. I don't want to work with spaghetti code, messy frameworks or dependencies hell.

**Comment by plumsirawit** [comment]
I propose the database should be DynamoDB. There are only 3 basic models so far: `User`, `Contest`, and `Task`.

The initial models' details are here:

### User

| Attribute      | Type |
| ----------- | ----------- |
| id      | ID       |
| fullname   | String        |
| email | String |
| displayname | String |
| contests | Contest[] |

### Contest

| Attribute | Type |
| ----------- | ------- |
| id | ID |
| shortname | String |
| title | String |
| fulltitle | String |
| country | String |
| language | String |
| langcode | String |
| date | String |
| users | User[] |
| logo | String |
| tasks | Task[] |

### Task

| Attribute | Type |
| ----------- | ------- |
| id | ID |
| markdown | String |

**Comment by plumsirawit** [comment]
Since relying everything on AWS is way too hard to use (and also an overkill), I therefore relax the constraints of preferring centralized services. I propose Auth0 as authN handler. For storage, S3 should have no problem. Styling will be relied on pure CSS for now (later migrations will be easy). State management would be just `useState` and `useEffect`. No redux or redux-saga for now. (might be migrations later if there are more things to do)

The APIs will be both from Nextjs and from AWS Lambda. The app will only call Nextjs API. Some requests will be then forwarded to AWS Lambda.

**Comment by plumsirawit** [comment]
The pages are `register`, `login`, `contests`, `tasks`, `task?p=...`, `index` and `editor`. User flow is obvious at this point.

**Comment by plumsirawit** [comment]
I realized this is way too overkill and too complex. I'm downgrading down back to using Firebase services: Firestore, Realtime Database, Storage and Authentication.

Potential migrations are kept in mind. The data model will be as portable as possible.
