### ISSUE TITLE
Implement functions

### ISSUE THREAD

**Issue by plumsirawit** [plumsirawit/task-pdf-writer#16]
Mostly CRUDs:

### Contest

- [x] create new contest
- [x] update contest info
- [x] delete contest
- [x] add new user to contest
- [x] delete user from contest

### Task

- [x] create new task in contest
- [x] list tasks in contest
- [x] update: move task from a contest to another
- [x] delete task
- [x] override current user on task
- [x] duplicate task
